### ISSUE TITLE
Login fails if user is in any community chats

### ISSUE THREAD

**Issue by gabrc52** [mautrix/facebook#308] opened 2023-05-29 01:40 UTC
I'm getting a `Failed to sync threads` with `ValueError: 'COMMUNITY' is not a valid ThreadFolder`.

I am in a Facebook community chat (a chat inside a Facebook space corresponding to a Facebook group) for some reason.

Since this fails exactly at login time, the bot seems to treat me as both logged in and logged out, so attempting to leave the community chat and try to log in again to see if I am able to log in is unsuccessful:

![image](https://github.com/mautrix/facebook/assets/24363938/e7ac5eca-7e5c-41d3-a06f-56e9a807bae1)

Log:

```
May 29 01:33:08 uplink-testing python[1711]: [2023-05-29 01:33:08,588] [ERROR@mau.user.@rgabriel:uplink.mit.edu] Failed to sync threads
May 29 01:33:08 uplink-testing python[1711]: Traceback (most recent call last):
May 29 01:33:08 uplink-testing python[1711]:   File "/opt/mautrix-facebook/lib/python3.10/site-packages/mautrix/types/util/serializable.py", line 101, in deserialize
May 29 01:33:08 uplink-testing python[1711]:     return cls(raw)
May 29 01:33:08 uplink-testing python[1711]:   File "/usr/lib/python3.10/enum.py", line 385, in __call__
May 29 01:33:08 uplink-testing python[1711]:     return cls.__new__(cls, value)
May 29 01:33:08 uplink-testing python[1711]:   File "/usr/lib/python3.10/enum.py", line 710, in __new__
May 29 01:33:08 uplink-testing python[1711]:     raise ve_exc
May 29 01:33:08 uplink-testing python[1711]: ValueError: 'COMMUNITY' is not a valid ThreadFolder
May 29 01:33:08 uplink-testing python[1711]: The above exception was the direct cause of the following exception:
May 29 01:33:08 uplink-testing python[1711]: Traceback (most recent call last):
May 29 01:33:08 uplink-testing python[1711]:   File "/opt/mautrix-facebook/lib/python3.10/site-packages/mautrix_facebook/user.py", line 539, in sync_threads
May 29 01:33:08 uplink-testing python[1711]:     await self._sync_threads(start_listen=start_listen)
May 29 01:33:08 uplink-testing python[1711]:   File "/opt/mautrix-facebook/lib/python3.10/site-packages/mautrix_facebook/user.py", line 559, in _sync_threads
May 29 01:33:08 uplink-testing python[1711]:     resp = await self.client.fetch_thread_list(thread_count=sync_count)
May 29 01:33:08 uplink-testing python[1711]:   File "/opt/mautrix-facebook/lib/python3.10/site-packages/maufbapi/http/api.py", line 59, in fetch_thread_list
May 29 01:33:08 uplink-testing python[1711]:     return await self.graphql(
May 29 01:33:08 uplink-testing python[1711]:   File "/opt/mautrix-facebook/lib/python3.10/site-packages/maufbapi/http/base.py", line 250, in graphql
May 29 01:33:08 uplink-testing python[1711]:     return response_type.deserialize(json_data)
May 29 01:33:08 uplink-testing python[1711]:   File "/opt/mautrix-facebook/lib/python3.10/site-packages/mautrix/types/util/serializable_attrs.py", line 375, in deserialize
May 29 01:33:08 uplink-testing python[1711]:     return _dict_to_attrs(cls, data)
May 29 01:33:08 uplink-testing python[1711]:   File "/opt/mautrix-facebook/lib/python3.10/site-packages/mautrix/types/util/serializable_attrs.py", line 198, in _dict_to_attrs
May 29 01:33:08 uplink-testing python[1711]:     new_items[name] = _try_deserialize(field_meta, value)
May 29 01:33:08 uplink-testing python[1711]:   File "/opt/mautrix-facebook/lib/python3.10/site-packages/mautrix/types/util/serializable_attrs.py", line 229, in _try_deserialize
May 29 01:33:08 uplink-testing python[1711]:     return _deserialize(field.type, value, field.default)
May 29 01:33:08 uplink-testing python[1711]:   File "/opt/mautrix-facebook/lib/python3.10/site-packages/mautrix/types/util/serializable_attrs.py", line 280, in _deserialize
May 29 01:33:08 uplink-testing python[1711]:     return [_deserialize(item_cls, item) for item in value]
May 29 01:33:08 uplink-testing python[1711]:   File "/opt/mautrix-facebook/lib/python3.10/site-packages/mautrix/types/util/serializable_attrs.py", line 280, in <listcomp>
May 29 01:33:08 uplink-testing python[1711]:     return [_deserialize(item_cls, item) for item in value]
May 29 01:33:08 uplink-testing python[1711]:   File "/opt/mautrix-facebook/lib/python3.10/site-packages/mautrix/types/util/serializable_attrs.py", line 267, in _deserialize
May 29 01:33:08 uplink-testing python[1711]:     return _dict_to_attrs(cls, value, default, default_if_empty=True)
May 29 01:33:08 uplink-testing python[1711]:   File "/opt/mautrix-facebook/lib/python3.10/site-packages/mautrix/types/util/serializable_attrs.py", line 198, in _dict_to_attrs
May 29 01:33:08 uplink-testing python[1711]:     new_items[name] = _try_deserialize(field_meta, value)
May 29 01:33:08 uplink-testing python[1711]:   File "/opt/mautrix-facebook/lib/python3.10/site-packages/mautrix/types/util/serializable_attrs.py", line 229, in _try_deserialize
May 29 01:33:08 uplink-testing python[1711]:     return _deserialize(field.type, value, field.default)
May 29 01:33:08 uplink-testing python[1711]:   File "/opt/mautrix-facebook/lib/python3.10/site-packages/mautrix/types/util/serializable_attrs.py", line 271, in _deserialize
May 29 01:33:08 uplink-testing python[1711]:     return cls.deserialize(value)
May 29 01:33:08 uplink-testing python[1711]:   File "/opt/mautrix-facebook/lib/python3.10/site-packages/mautrix/types/util/serializable.py", line 103, in deserialize
May 29 01:33:08 uplink-testing python[1711]:     raise SerializerError() from e
May 29 01:33:08 uplink-testing python[1711]: mautrix.types.util.serializable.SerializerError
```

This error disappears if attempting to login again but from a fresh database.

**Comment by tulir** [comment] 2023-05-29 09:08
Duplicate of #289

**Closed by tulir** 2023-05-29 09:08 UTC
Labels: bug
